export const products = [
  {
    id: 1,
    img: "https://foodal.com/wp-content/uploads/2014/09/must-have-kitchen-gadets.jpg",
    name: "Kitchen Products",
    stock: 20,
    discription: "kitchen item and all kitchen equipements",
  },
  {
    id: 2,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVT0E2GojskstD2kPhXu5yg1aNO4UKlnHC6Q&usqp=CAU",
    name: "Fashion",
    stock: 20,
    discription: "all type of garment and clothings",
  },
  {
    id: 3,
    img: "https://thumbs.dreamstime.com/b/many-used-modern-electronic-gadgets-use-white-floor-reuse-recycle-concept-top-view-153892483.jpg",
    name: "Electroinics items",
    stock: 20,
    discription: "All type of electronics mobile phone etc",
  },
  {
    id: 4,
    img: "https://3.imimg.com/data3/KQ/DM/MY-10863971/footwear-500x500.png",
    name: "Footware",
    stock: 20,
    discription: "All type of footware and boots",
  },
  {
    id: 5,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtgcSRamq_SDT356YjSRdo7eqf7yWxQrn5xjPlKrPFqOQkm3_kyDcJfgIFugmD_wuzN6k&usqp=CAU",
    name: "Health products",
    stock: 20,
    discription: "Health products ",
  },
  {
    id: 6,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT08rulMkvWxsr0vKbuCgGyFbIXetk9h3iVAkse6lmz-a_gbCoQlzLV5SVATZGgBqfZO50&usqp=CAU",
    name: "Fitness Products",
    stock: 20,
    discription: "All type of fitenss products",
  },
  {
    id: 7,
    img: "https://i.pinimg.com/736x/53/06/f1/5306f17104d3206883a3fa37b5fb7139.jpg",
    name: "Appliances",
    stock: 20,
    discription: "All type of appliances",
  },
  {
    id: 8,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSzzbxSNpckYcYvUr7_PDbM1DJYZfIaoaQWRA&usqp=CAU",
    name: "Home appliances",
    stock: 20,
    discription: "All kind of sofa,dining, wardrobe etc home products",
  },
  {
    id: 9,
    img: "https://img3.exportersindia.com/product_images/bc-full/dir_178/5327018/grocery-products-1510312058-3444389.jpeg",
    name: "Grocery products",
    stock: 20,
    discription: "All type of grocery and food products",
  },
  {
    id: 10,
    img: "https://thumbs.dreamstime.com/b/cosmetic-woman-makeup-beauty-products-decorated-star-confetti-coral-table-top-view-flat-lay-cosmetic-woman-makeup-148122166.jpg",
    name: "Beauty products",
    stock: 20,
    discription: "All type of beauty products",
  },
];

export const floatingProducts = [
  {
    id: 1,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVHnlbX64KPSB3FBHfSSg8YmSW-SbDP0-weA&usqp=CAU",
    name: "Man",
  },
  {
    id: 2,
    img: "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1610416577-vans-1610416571.jpg",
    name: "Shoe",
  },
  {
    id: 3,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSW4Jrq8nnX8qr5QRUSkhYaP4_DCB-J27pkDg&usqp=CAU",
    name: "Pant",
  },
  {
    id: 4,
    img: "https://m.media-amazon.com/images/I/71gkRrWoOfL._SL1500_.jpg",
    name: "Pan",
  },
];

export const allProducts = [
  {
    id: 1,
    img: "https://rukminim1.flixcart.com/image/416/416/kae95e80/television/f/6/y/realme-tv-32-original-imafrz79pweqeafh.jpeg?q=70",
    name: "TV",
    discription: "TV",
    totalStock: "10",
    price: "10",
  },
  {
    id: 2,
    img: "https://rukminim1.flixcart.com/image/416/416/kae95e80/television/f/6/y/realme-tv-32-original-imafrz79pweqeafh.jpeg?q=70",
    name: "TV",
    discription: "TV",
    totalStock: "10",
    price: "10",
  },
  {
    id: 3,
    img: "https://rukminim1.flixcart.com/image/416/416/kae95e80/television/f/6/y/realme-tv-32-original-imafrz79pweqeafh.jpeg?q=70",
    name: "TV",
    discription: "TV",
    totalStock: "10",
    price: "10",
  },
  {
    id: 4,
    img: "https://rukminim1.flixcart.com/image/416/416/kae95e80/television/f/6/y/realme-tv-32-original-imafrz79pweqeafh.jpeg?q=70",
    name: "TV",
    discription: "TV",
    totalStock: "10",
    price: "10",
  },
  {
    id: 1,
    img: "https://rukminim1.flixcart.com/image/416/416/kae95e80/television/f/6/y/realme-tv-32-original-imafrz79pweqeafh.jpeg?q=70",
    name: "TV",
    discription: "TV",
    totalStock: "10",
    price: "10",
  },
  {
    id: 5,
    img: "https://rukminim1.flixcart.com/image/416/416/kae95e80/television/f/6/y/realme-tv-32-original-imafrz79pweqeafh.jpeg?q=70",
    name: "TV",
    discription: "TV",
    totalStock: "10",
    price: "10",
  },
  {
    id: 6,
    img: "https://rukminim1.flixcart.com/image/416/416/kae95e80/television/f/6/y/realme-tv-32-original-imafrz79pweqeafh.jpeg?q=70",
    name: "TV",
    discription: "TV",
    totalStock: "10",
    price: "10",
  },
];
